name = "mynote-api"
main = "src/worker/index.ts"
compatibility_date = "2024-01-01"

# 开发环境 D1 数据库
[[d1_databases]]
binding = "DB"
database_name = "local-mynote-db"
database_id = "a79ea03c-834e-4a9a-b3a9-f3e17df58962"

# KV 命名空间绑定（可选）
# [[kv_namespaces]]
# binding = "CACHE"
# id = "YOUR_KV_ID"

# 生产环境
[env.production]
name = "mynote-api"

# 生产环境 D1 数据库
[[env.production.d1_databases]]
binding = "DB"
database_name = "mynote-db"
database_id = "c96e2e7a-2dc2-434c-91a6-fd9b98f85cb3"

[dev]
port = 8787
local_protocol = "http"



[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
